import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fn_notifications, FnNotificationsWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Structured JSON logging for production
config :logger, level: :info

# Disable debug logging in production
config :logger,
  compile_time_purge_matching: [
    [level_lower_than: :info]
  ]

config :logger, :default_handler, formatter: LoggerJSON.Formatters.BasicLogger

config :logger_json, :backend,
  metadata: [:correlation_id, :request_id, :user_id, :event_type, :notification_id],
  json_encoder: Jason,
  formatter: LoggerJSON.Formatters.BasicLogger

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
